---
namespace: tonyskapunk
name: beat
# Always leave patch version as .0
# Patch version is replaced from commit date and git hash
# example: 1.2.202311141650+git0a1b2c3
version: 1.2.0
readme: README.md
authors:
  - Tony Garcia
description: Role and module to print internet time in beats
license:
  - GPL-3.0-or-later
tags:
  - beat
  - internettime
  - time
repository: http://github.com/tonyskapunk/beat-ansible-collection
documentation: http://github.com/tonyskapunk/beat-ansible-collection
homepage: http://github.com/tonyskapunk/beat-ansible-collection
issues: http://github.com/tonyskapunk/beat-ansible-collection/issues
build_ignore:
  - .github*
