---
- name: Converge
  hosts: molecule
  gather_facts: false
  tasks:
    - name: Include beat_role with centibeats (default)
      ansible.builtin.include_role:
        name: beat_role

    - name: Include beat_role (without centibeats)
      ansible.builtin.include_role:
        name: beat_role
      vars:
        beat_role_centibeats: false
