---
- name: Get beat time
  tonyskapunk.beat.beat:
    centibeats: "{{ beat_role_centibeats | bool }}"
  register: beat_time

- name: Print beat time
  ansible.builtin.debug:
    msg: "The beat time is {{ beat_time.beats }}"
