galaxy_info:
  author: Tony Garcia
  description: Use beat to print internet time
  license: GPL-3.0-only
  min_ansible_version: 2.9.10
  platforms:
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - beat
    - internettime
    - time
