---
- name: Beat playbook
  hosts: localhost
  tasks:

  - name: Test beat module
    tonyskapunk.beat.beat:
    register: test_beat

  - name: Print beat
    debug:
      msg: '{{ test_beat }}'
  
  - name: Test beat module with centibeats
    tonyskapunk.beat.beat:
      centibeats: true
    register: test_beat

  - name: Print beat with centibeats
    debug:
      msg: '{{ test_beat }}'

  - name: Include beat role
    ansible.builtin.include_role:
      name: tonyskapunk.beat.beat_role
