name: Ansible Galaxy Publish
on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add release, date and commit hash to version in galaxy.yml
        id: galaxy
        run: >
          ts=$(TZ=UTC0 git show ${{ github.sha }} --no-patch --format=%cd --date=format-local:'%Y%m%d%H%M')
          sha=$(echo "${{ github.sha }}" | cut -c1-7);
          sed -i -r "s/^(version: .*)\.0$/\1.${ts}.git${sha}/" galaxy.yml;
          grep ^version galaxy.yml;
          awk '/^version/ {printf("ver=%s", $2)}' galaxy.yml >> "${GITHUB_OUTPUT}"

      - name: Ansible Publish to Galaxy
        uses: ansible/ansible-publish-action@v1.0.0
        with:
          api_key: ${{ secrets.ANSIBLE_GALAXY_TOKEN }}

      - name: Notify failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          ENABLE_ESCAPES: true
          MSG_MINIMAL: true
          SLACK_COLOR: ${{ job.status }}
          SLACK_FOOTER: "version: ${{ steps.galaxy.outputs.ver }}"
          SLACKIFY_MARKDOWN: true
          SLACK_MESSAGE: >
            URL: [${{ github.workflow }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}/checks)
          SLACK_TITLE: 🔴 Galaxy Publication Failure
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

