---
name: Role testing

on:
  push:
    branches:
      - "main"
  pull_request:
  schedule:
    - cron: '0 9 * * *'

env:
  NAMESPACE: tonyskapunk
  COLLECTION_NAME: beat

jobs:
  molecule:
    name: Molecule ${{ matrix.ver.molecule }}
    strategy:
      matrix:
        ver:
          - python: "3.11"
            molecule: v6.0.3
          - python: "3.12"
            molecule: v24.6.0

    runs-on: ubuntu-24.04
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ansible_collections/${{ env.NAMESPACE }}/${{ env.COLLECTION_NAME }}

      - name: Set up Python ${{ matrix.ver.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.ver.python }}

      - name: Install molecule (${{ matrix.ver.molecule }})
        run: pip install https://github.com/ansible/molecule/archive/${{ matrix.ver.molecule }}.tar.gz --disable-pip-version-check

      - name: Install requirements
        run: >
          ansible-galaxy install -r 
          ./ansible_collections/${{ env.NAMESPACE }}/${{ env.COLLECTION_NAME }}/roles/beat_role/molecule/*/requirements.yml

      - name: Run molecule tests
        run: >
          molecule test --all
        working-directory: ./ansible_collections/${{ env.NAMESPACE }}/${{ env.COLLECTION_NAME }}/roles/beat_role
